# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: ./App/Gateway/
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081
    networks:
      default:
  
  identity:
    image: identity
    depends_on:
      - db-identity
    build:
      context: ./App/Services/Application/Identity
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
#      - ASPNETCORE_HTTPS_PORTS=5001
    networks:
      default: 
    links:
      - db-identity
        
  db-identity:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./Volumes/Identity:/var/lib/postgresql/data
    ports:
      -  5011:5432
networks:
  default:
    driver: "bridge"
