# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: ./App/Gateway/
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081
      - JwtConfiguration__Authority=identity:5001
      - JwtConfiguration__Audience=gateway:8000
    networks:
      default:
  
  identity:
    image: identity
    depends_on:
      - db-identity
    build:
      context: ./App/Services/Application/Identity
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
#      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__IdentityDb=User ID=postgres;Password=admin;Host=db-identity;Port=5432;Database=postgres;Pooling=true;
      - ConnectionStrings__IdentityDbHost=User ID=postgres;Password=admin;Host=localhost;Port=5011;Database=postgres;Pooling=true;
      - JwtConfiguration__Issuer=identity:5001
      - JwtConfiguration__Audience=gateway:8000
      - JwtConfiguration__SecurityKey=55744df1-a4c9-4dda-a4bf-e2449b35ec0c
      - JwtConfiguration__ExpirationTimeInMinutes=120
    networks:
      default: 
        
  db-identity:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      
      
    volumes:
      - ./Volumes/Identity:/var/lib/postgresql/data
    ports:
      -  5011:5432
    networks:
      default:


networks:
  default:
    driver: "bridge"
